export enum ProctoringEventType {
  TAB_HIDDEN = 'TAB_HIDDEN',
  WINDOW_BLUR = 'WINDOW_BLUR',
  WINDOW_FOCUS = 'WINDOW_FOCUS',
  FORCE_SUBMIT_TRIGGERED = 'FORCE_SUBMIT_TRIGGERED',
}

export enum ExamSessionStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  AUTO_SUBMITTED = 'AUTO_SUBMITTED',
  EXPIRED = 'EXPIRED',
}
