export enum UserRoleCode {
  MASTER_ADMIN = 'MASTER_ADMIN',
  ADMIN = 'ADMIN',
  PARTICIPANT = 'PARTICIPANT',
}

export enum PermissionScopeType {
  GLOBAL = 'GLOBAL',
  SUB_TEST = 'SUB_TEST',
}

export enum AccessActionType {
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REVOKED = 'ROLE_REVOKED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  USER_LOCKED = 'USER_LOCKED',
  USER_UNLOCKED = 'USER_UNLOCKED',
}

export enum PermissionCode {
  QUESTION_CREATE = 'QUESTION_CREATE',
  QUESTION_UPDATE = 'QUESTION_UPDATE',
  QUESTION_DELETE = 'QUESTION_DELETE',
  QUESTION_VIEW_DRAFT = 'QUESTION_VIEW_DRAFT',
  QUESTION_PUBLISH = 'QUESTION_PUBLISH',
  QUESTION_REVIEW = 'QUESTION_REVIEW',
  SUBTEST_VIEW = 'SUBTEST_VIEW',
  EXAM_RESULT_VIEW = 'EXAM_RESULT_VIEW',
  EXAM_RESULT_EXPORT = 'EXAM_RESULT_EXPORT',
  USER_VIEW = 'USER_VIEW',
  USER_SUSPEND = 'USER_SUSPEND',
  ADMIN_ROLE_ASSIGN = 'ADMIN_ROLE_ASSIGN',
  ADMIN_ROLE_REVOKE = 'ADMIN_ROLE_REVOKE',
  ADMIN_PERMISSION_GRANT = 'ADMIN_PERMISSION_GRANT',
  ADMIN_PERMISSION_REVOKE = 'ADMIN_PERMISSION_REVOKE',
  AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
}
